#!/bin/bash

function createCompany() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/company.enset.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/company.enset.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-company --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/company.enset.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy company's CA cert to company's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.enset.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.enset.com/msp/tlscacerts/ca.crt"

  # Copy company's CA cert to company's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.enset.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.enset.com/tlsca/tlsca.company.enset.com-cert.pem"

  # Copy company's CA cert to company's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.enset.com/ca"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.enset.com/ca/ca.company.enset.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-company --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-company --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-company --id.name companyadmin --id.secret companyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls" --enrollment.profile tls --csr.hosts peer0.company.enset.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/company.enset.com/peers/peer0.company.enset.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.enset.com/users/User1@company.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.enset.com/users/User1@company.enset.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://companyadmin:companyadminpw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.enset.com/users/Admin@company.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.enset.com/users/Admin@company.enset.com/msp/config.yaml"
}

function createCustomer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/customer.enset.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/customer.enset.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-customer --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-customer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-customer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-customer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-customer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/customer.enset.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy customer's CA cert to customer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/customer.enset.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/customer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/customer.enset.com/msp/tlscacerts/ca.crt"

  # Copy customer's CA cert to customer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/customer.enset.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/customer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/customer.enset.com/tlsca/tlsca.customer.enset.com-cert.pem"

  # Copy customer's CA cert to customer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/customer.enset.com/ca"
  cp "${PWD}/organizations/fabric-ca/customer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/customer.enset.com/ca/ca.customer.enset.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-customer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-customer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-customer --id.name customeradmin --id.secret customeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/customer.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls" --enrollment.profile tls --csr.hosts peer0.customer.enset.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/customer.enset.com/peers/peer0.customer.enset.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.enset.com/users/User1@customer.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/customer.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/customer.enset.com/users/User1@customer.enset.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://customeradmin:customeradminpw@localhost:8054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.enset.com/users/Admin@customer.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/customer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/customer.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/customer.enset.com/users/Admin@customer.enset.com/msp/config.yaml"
}

function createSupplier1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/supplier1.enset.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/supplier1.enset.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-supplier1 --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier1.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/supplier1.enset.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy supplier1's CA cert to supplier1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier1.enset.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier1.enset.com/msp/tlscacerts/ca.crt"

  # Copy supplier1's CA cert to supplier1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier1.enset.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier1.enset.com/tlsca/tlsca.supplier1.enset.com-cert.pem"

  # Copy supplier1's CA cert to supplier1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier1.enset.com/ca"
  cp "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier1.enset.com/ca/ca.supplier1.enset.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-supplier1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-supplier1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-supplier1 --id.name supplier1admin --id.secret supplier1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-supplier1 -M "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier1.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-supplier1 -M "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls" --enrollment.profile tls --csr.hosts peer0.supplier1.enset.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/supplier1.enset.com/peers/peer0.supplier1.enset.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-supplier1 -M "${PWD}/organizations/peerOrganizations/supplier1.enset.com/users/User1@supplier1.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier1.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier1.enset.com/users/User1@supplier1.enset.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://supplier1admin:supplier1adminpw@localhost:11054 --caname ca-supplier1 -M "${PWD}/organizations/peerOrganizations/supplier1.enset.com/users/Admin@supplier1.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier1.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier1.enset.com/users/Admin@supplier1.enset.com/msp/config.yaml"
}

function createSupplier2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/supplier2.enset.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/supplier2.enset.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-supplier2 --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-supplier2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-supplier2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-supplier2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-supplier2.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/supplier2.enset.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy supplier2's CA cert to supplier2's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier2.enset.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier2.enset.com/msp/tlscacerts/ca.crt"

  # Copy supplier2's CA cert to supplier2's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier2.enset.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier2.enset.com/tlsca/tlsca.supplier2.enset.com-cert.pem"

  # Copy supplier2's CA cert to supplier2's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier2.enset.com/ca"
  cp "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier2.enset.com/ca/ca.supplier2.enset.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-supplier2 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-supplier2 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-supplier2 --id.name supplier2admin --id.secret supplier2adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-supplier2 -M "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier2.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-supplier2 -M "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls" --enrollment.profile tls --csr.hosts peer0.supplier2.enset.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/supplier2.enset.com/peers/peer0.supplier2.enset.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-supplier2 -M "${PWD}/organizations/peerOrganizations/supplier2.enset.com/users/User1@supplier2.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier2.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier2.enset.com/users/User1@supplier2.enset.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://supplier2admin:supplier2adminpw@localhost:10054 --caname ca-supplier2 -M "${PWD}/organizations/peerOrganizations/supplier2.enset.com/users/Admin@supplier2.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier2.enset.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier2.enset.com/users/Admin@supplier2.enset.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/enset.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/enset.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/enset.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/enset.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/enset.com/msp/tlscacerts/tlsca.enset.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/enset.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/enset.com/tlsca/tlsca.enset.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054
9054
9054
9054
9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/enset.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054
9054
9054
9054
9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls" --enrollment.profile tls --csr.hosts orderer.enset.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/msp/tlscacerts/tlsca.enset.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054
9054
9054
9054
9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/enset.com/users/Admin@enset.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/enset.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/enset.com/users/Admin@enset.com/msp/config.yaml"
}
