---

Organizations:
  - &OrdererOrganization
    
    Name: OrdererOrganization
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/enset.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.enset.com:11050
  
  - &Company

    Name: CompanyOrganization
    ID: CompanyMSP
    MSPDir: ../organizations/peerOrganizations/company.enset.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CompanyMSP.admin', 'CompanyMSP.peer', 'CompanyMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('CompanyMSP.admin', 'CompanyMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('CompanyMSP.admin')"
  
  - &SupplierA

    Name: SupplierAOrganization
    ID: SupplierAMSP
    MSPDir: ../organizations/peerOrganizations/suppliera.enset.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('SupplierAMSP.admin', 'SupplierAMSP.peer', 'SupplierAMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('SupplierAMSP.admin', 'SupplierAMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('SupplierAMSP.admin')"

Capabilities:

  Channel: &ChannelCapabilities
    V2_0: true
  
  Orderer: &OrdererCapabilities
    V2_0: true
  
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

  Addresses:
    - orderer.enset.com:11050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    
Channel: &ChannelDefaults

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.enset.com
            Port: 11050
            ClientTLSCert: ../organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/enset.com/orderers/orderer.enset.com/tls/server.crt
      Organizations:
        - *OrdererOrganization
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Company
        - *SupplierA
      Capabilities: *ApplicationCapabilities