OrdererOrgs:
  - Name: Orderer
    Domain: enset.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - localhost
      - Hostname: orderer2
        SANS:
          - localhost
      - Hostname: orderer3
        SANS:
          - localhost
      - Hostname: orderer4
        SANS:
          - localhost